add env-cmd and uncomment env variables script in deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,70 +50,70 @@ jobs:
           yarn install --frozen-lockfile
           yarn --cwd functions install --frozen-lockfile
 
-      # - name: Set App Environment Settings
-      #   env:
-      #     MASTER_SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
-      #     PROD_SERVICE_ACCOUNT: ${{ secrets.PROD_SERVICE_ACCOUNT }}
-      #     GITHUB_HEAD_REF: ${{ github.head_ref }}
-      #     GITHUB_REF: ${{ github.ref }}
-      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
-      #   run: |
-      #     set -o pipefail
+      - name: Set App Environment Settings
+        env:
+          MASTER_SERVICE_ACCOUNT: ${{ secrets.MASTER_SERVICE_ACCOUNT }}
+          PROD_SERVICE_ACCOUNT: ${{ secrets.PROD_SERVICE_ACCOUNT }}
+          GITHUB_HEAD_REF: ${{ github.head_ref }}
+          GITHUB_REF: ${{ github.ref }}
+          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
+        run: |
+          set -o pipefail
 
-      #     # Throw a clear error if FIREBASE_TOKEN secret is not set
-      #     if [ -z "$FIREBASE_TOKEN" ];
-      #       then
-      #         errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
-      #         echo "::error ::$errMsg"
-      #         exit 1
-      #     fi
+          # Throw a clear error if FIREBASE_TOKEN secret is not set
+          if [ -z "$FIREBASE_TOKEN" ];
+            then
+              errMsg="\"FIREBASE_TOKEN\" github secret is required to load project configuration. Visit https://github.com/${{ github.repository }}/settings/secrets to set."
+              echo "::error ::$errMsg"
+              exit 1
+          fi
 
-      #     # Get branch name from github ref (i.e. refs/heads/master -> master)
-      #     gitBranch=${GITHUB_REF##*/}
+          # Get branch name from github ref (i.e. refs/heads/master -> master)
+          gitBranch=${GITHUB_REF##*/}
 
-      #     # Find the config associated to the firebase project in .firebaserc (falling back to default)
-      #     gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
-      #     appName=test2
-      #     echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
+          # Find the config associated to the firebase project in .firebaserc (falling back to default)
+          gcloudProject=$(cat .firebaserc | jq -r --arg alias "$gitBranch" '.projects[$alias] // .projects.default')
+          appName=test2
+          echo "Setting environment for branch: $gitBranch, project: $gcloudProject, and app: $appName..."
 
-      #     # Set variables to environment to be used in later steps
-      #     echo "GCLOUD_PROJECT=$gcloudProject" >> $GITHUB_ENV
+          # Set variables to environment to be used in later steps
+          echo "GCLOUD_PROJECT=$gcloudProject" >> $GITHUB_ENV
 
-      #     # Get value of Service Account associated with branch (i.e. STAGE_SERVICE_ACCOUNT)
-      #     branchPrefix=$(echo $gitBranch | tr a-z A-Z | tr - _)
-      #     branchSaKey="${branchPrefix}_SERVICE_ACCOUNT"
-      #     branchSa=$(eval echo \$${branchSaKey})
-      #     if [[ ! -z "${branchSa}" ]]; then
-      #       echo Using service account with key \"$branchSaKey\"
-      #       serviceAccount=$branchSa
-      #     else
-      #       echo Falling back to service account with key "DEVELOP_SERVICE_ACCOUNT"
-      #       serviceAccount=$DEVELOP_SERVICE_ACCOUNT
-      #     fi
+          # Get value of Service Account associated with branch (i.e. STAGE_SERVICE_ACCOUNT)
+          branchPrefix=$(echo $gitBranch | tr a-z A-Z | tr - _)
+          branchSaKey="${branchPrefix}_SERVICE_ACCOUNT"
+          branchSa=$(eval echo \$${branchSaKey})
+          if [[ ! -z "${branchSa}" ]]; then
+            echo Using service account with key \"$branchSaKey\"
+            serviceAccount=$branchSa
+          else
+            echo Falling back to service account with key "DEVELOP_SERVICE_ACCOUNT"
+            serviceAccount=$DEVELOP_SERVICE_ACCOUNT
+          fi
 
-      #     echo "Service Account selected for projectId $(echo $serviceAccount | jq .project_id)"
+          echo "Service Account selected for projectId $(echo $serviceAccount | jq .project_id)"
 
-      #     # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
-      #     echo "Generating Service Account File..."
-      #     echo "$(echo $serviceAccount | jq .)" > $HOME/serviceAccount.json
-      #     echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/serviceAccount.json" >> $GITHUB_ENV
+          # Generate Service Account file required to prevent credential error during functions unit tests (jq used to format)
+          echo "Generating Service Account File..."
+          echo "$(echo $serviceAccount | jq .)" > $HOME/serviceAccount.json
+          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/serviceAccount.json" >> $GITHUB_ENV
 
-      #     # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
-      #     # NOTE: databaseURL is intentionally removed since it is set above
-      #     firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
-      #       $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
-      #         tr '\n' ' ' | \
-      #         sed 's/.*initializeApp(//g' | \
-      #         sed 's/);//g' | \
-      #         jq -r 'to_entries[] | [.key, (.value | tojson)] | join("::")' | \
-      #         sed 's/:"/:/g; s/^/echo \"REACT_APP_FB_/g' \
-      #     )
+          # Use Firebase SDK API to get the app's configuration and export to REACT_APP prefixed environment variables
+          # NOTE: databaseURL is intentionally removed since it is set above
+          firebaseConfig=$(npx firebase --project $gcloudProject apps:sdkconfig WEB \
+            $(npx firebase --project $gcloudProject apps:list WEB | grep $appName | awk '{ print $4}') | \
+              tr '\n' ' ' | \
+              sed 's/.*initializeApp(//g' | \
+              sed 's/);//g' | \
+              jq -r 'to_entries[] | [.key, (.value | tojson)] | join("::")' | \
+              sed 's/:"/:/g; s/^/echo \"REACT_APP_FB_/g' \
+          )
 
-      #     # Loop through each line of config and evaluate to export env vars
-      #     while IFS= read -r line; do
-      #       echo Evaluating: $line
-      #       eval $line >> $GITHUB_ENV
-      #     done <<< "$firebaseConfig"
+          # Loop through each line of config and evaluate to export env vars
+          while IFS= read -r line; do
+            echo Evaluating: $line
+            eval $line >> $GITHUB_ENV
+          done <<< "$firebaseConfig"
 
       - name: Verify App
         run: |
